// 文章相关
export const ARTICLE_LIST = 'ARTICLE_LIST'
export const ADD_ARTICLE_LIST = 'ADD_ARTICLE_LIST'
export const GET_ARTICLE_LIST_FAILURE = 'GET_ARTICLE_LIST_FAILURE'
export const LOADING_ARTICLE = 'LOADING_ARTICLE'
export const ARTICLE_CONTNET = 'ARTICLE_CONTNET'
export const GET_ARTICLE_CONTENT_FAILURE = 'GET_ARTICLE_CONTENT_FAILURE'
export const GET_PRENEXT_LIST = 'GET_PRENEXT_LIST'

// 相册相关
export const GET_IMAGE_LIST_BY_TIME = 'GET_IMAGE_LIST_BY_TIME'
export const GET_IMAGES_LIST_BY_CITY = 'GET_IMAGES_LIST_BY_CITY'
export const GET_IMAGES_BY_CITYID = 'GET_IMAGES_BY_CITYID'
export const GET_IMAGE_LIST_FAILURE = 'GET_IMAGE_LIST_FAILURE'
export const VOTE_IMAGE = 'VOTE_IMAGE'
export const ADD_IMAGE_LIST = 'ADD_IMAGE_LIST'
export const LOADING_IMAGE = 'LOADING_IMAGE'

// 书籍相关
export const GET_BOOK_LIST = 'GET_BOOK_LIST'
export const GET_BOOK_LIST_FAILURE = 'GET_BOOK_LIST_FAILURE'
export const VOTE_BOOK = 'VOTE_BOOK'
export const LOADING_BOOK = 'LOADING_BOOK'

// 关于
export const GET_ABOUT_INFO = 'GET_ABOUT_INFO'
export const GET_ABOUT_INFO_FAILURE = 'GET_ABOUT_INFO_FAILURE'
