export const ARTICLE_LIST = 'ARTICLE_LIST'
export const ADD_ARTICLE_LIST = 'ADD_ARTICLE_LIST'
export const GET_ARTICLE_LIST_FAILURE = 'GET_ARTICLE_LIST_FAILURE'

export const ARTICLE_CONTNET = 'ARTICLE_CONTNET'
export const GET_ARTICLE_CONTENT_FAILURE = 'GET_ARTICLE_CONTENT_FAILURE'

export const GET_IMAGE_LIST = 'GET_IMAGE_LIST'
export const GET_IMAGE_LIST_FAILURE = 'GET_IMAGE_LIST_FAILURE'
export const VOTE_IMAGE = 'VOTE_IMAGE'

export const GET_BOOK_LIST = 'GET_BOOK_LIST'
export const GET_BOOK_LIST_FAILURE = 'GET_BOOK_LIST_FAILURE'
export const VOTE_BOOK = 'VOTE_BOOK'