export const ARTICLE_LIST = 'ARTICLE_LIST'
export const ADD_ARTICLE_LIST = 'ADD_ARTICLE_LIST'
export const GET_ARTICLE_LIST_FAILURE = 'GET_ARTICLE_LIST_FAILURE'
export const LOADING_ARTICLE = 'LOADING_ARTICLE'

export const ARTICLE_CONTNET = 'ARTICLE_CONTNET'
export const GET_ARTICLE_CONTENT_FAILURE = 'GET_ARTICLE_CONTENT_FAILURE'

export const GET_PRENEXT_LIST = 'GET_PRENEXT_LIST'

export const GET_IMAGE_LIST = 'GET_IMAGE_LIST'
export const GET_IMAGE_LIST_FAILURE = 'GET_IMAGE_LIST_FAILURE'
export const VOTE_IMAGE = 'VOTE_IMAGE'
export const ADD_IMAGE_LIST = 'ADD_IMAGE_LIST'
export const LOADING_IMAGE = 'LOADING_IMAGE'

export const GET_BOOK_LIST = 'GET_BOOK_LIST'
export const GET_BOOK_LIST_FAILURE = 'GET_BOOK_LIST_FAILURE'
export const VOTE_BOOK = 'VOTE_BOOK'
export const ADD_BOOK_LIST = 'ADD_BOOK_LIST'
export const LOADING_BOOK = 'LOADING_BOOK'

export const GET_ABOUT_INFO = 'GET_ABOUT_INFO'
export const GET_ABOUT_INFO_FAILURE = 'GET_ABOUT_INFO_FAILURE'
